import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { FormattedMessage, useIntl } from 'react-intl';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const intl = useIntl();

  return (
    <div className={styles.container}>
      <Head>
        <title>{intl.formatMessage({ defaultMessage: 'Create Next App', id: 'frontpage.pageTitle' })}</title>
        imf
        <meta
          name="description"
          content={intl.formatMessage({
            defaultMessage: 'Generated by create next app',
            id: 'frontpage.pageDescription',
          })}
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <FormattedMessage
            id="frontpage.title"
            defaultMessage="Welcome to {link}"
            values={{ link: <a href="https://nextjs.org">Next.js!</a> }}
          />
        </h1>

        <p className={styles.description}>
          <FormattedMessage
            id="frontpage.description"
            defaultMessage="Get started by editing {code}"
            values={{
              code: <code className={styles.code}>pages/index.tsx</code>,
            }}
          />
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>
              <FormattedMessage defaultMessage="Documentation →" id="frontpage.documentation.title" />
            </h2>
            <p>
              <FormattedMessage
                defaultMessage="Find in-depth information about Next.js features and API."
                id="frontpage.documentation.description"
              />
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>
              <FormattedMessage defaultMessage="Learn →" id="frontpage.learn.title" />
            </h2>
            <p>
              <FormattedMessage
                defaultMessage="Learn about Next.js in an interactive course with quizzes!"
                id="frontpage.learn.description"
              />
            </p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/canary/examples" className={styles.card}>
            <h2>
              <FormattedMessage defaultMessage="Examples →" id="frontpage.example.title" />
            </h2>
            <p>
              <FormattedMessage
                defaultMessage="Discover and deploy boilerplate example Next.js projects."
                id="frontpage.example.description"
              />
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>
              <FormattedMessage defaultMessage="Deploy →" id="frontpage.deploy.title" />
            </h2>
            <p>
              <FormattedMessage
                defaultMessage="Instantly deploy your Next.js site to a public URL with Vercel."
                id="frontpage.deploy.description"
              />
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <FormattedMessage
            id="frontpage.poweredByNext"
            defaultMessage="Powered by {nextjs}"
            values={{
              nextjs: (
                <span className={styles.logo}>
                  <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span>
              ),
            }}
          />
        </a>
      </footer>
    </div>
  );
};

export default Home;
